global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: AKIA27XQ5W5VWSRAXWO7
        secret_key: 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
        port: 9090